
name: Angular-CI-Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build Angular app
        run: pnpm run build:prod

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/haciendola-tech-frontend-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
